services:
  postgres:
    image: postgres:16-alpine
    container_name: passage-postgres
    environment:
      POSTGRES_DB: passage_db
      POSTGRES_USER: passage_user
      POSTGRES_PASSWORD: passage_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - passage-network

  redis:
    image: redis:7-alpine
    container_name: passage-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - passage-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: passage-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - passage-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  passage-network:
    driver: bridge